# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

init:
- git config --global core.autocrlf input

shallow_clone: true

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 12"
    QT5: C:\Qt\5.5\msvc2013
  - CMAKE_GENERATOR: "Visual Studio 12 Win64"
    QT5: C:\Qt\5.5\msvc2013_64

matrix:
  fast_finish: true

configuration: Debug

before_build:
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%" -DENABLE_GUI=ON

build:
  project: build\apitrace.sln
  verbosity: minimal

after_build:
- cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%
- cmake --build build --config "%CONFIGURATION%" --target check -- %MSBUILD_FLAGS%
- cmake --build build --config "%CONFIGURATION%" --target package -- %MSBUILD_FLAGS%

#artifacts:
#- path: build/apitrace-*.7z
#  name: apitrace
