# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

init:
- git config --global core.autocrlf input

shallow_clone: true

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2015

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015"
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

matrix:
  fast_finish: true

before_build:
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -T v140_xp -DCMAKE_SYSTEM_VERSION=5.1 -DENABLE_GUI=OFF

build_script:
- if "%APPVEYOR_REPO_TAG%"=="true" (set CONFIGURATION=RelWithDebInfo) else (set CONFIGURATION=Debug)
- cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

after_build:
- cmake --build build --config "%CONFIGURATION%" --target check -- %MSBUILD_FLAGS%
- cmake --build build --config "%CONFIGURATION%" --target package -- %MSBUILD_FLAGS%

artifacts:
- path: build/apitrace-*.7z

deploy:
  provider: GitHub
  auth_token:
    secure: a79IHXDoZN60ADwPX1OfJYJUjaWSeKWqFfQu+531AaSuH5a03sR8ZKeNWutklAQU
  artifact: /.*\.7z/
  on:
    appveyor_repo_tag: true
